"""empty message

Revision ID: e4f1cd47a5e5
Revises: None
Create Date: 2018-05-02 17:22:14.369680

"""

# revision identifiers, used by Alembic.
revision = 'e4f1cd47a5e5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('rehearsal', sa.Boolean(), nullable=True),
    sa.Column('wedding', sa.Boolean(), nullable=True),
    sa.Column('brunch', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rsvps')
    # ### end Alembic commands ###
